release/1.0.0
theCrystalKitty/algorithms-homework pull request #2
Opened 2024-10-15 05:30 UTC by theCrystalKitty

2024-10-18 07:13 UTC, rootCurse requested changes

2024-10-18 07:13 UTC, rootCurse commented on homework1/insertionSort.ts
> +//Difficulty: O(n log(n))
Неправильная сложность

2024-10-18 07:13 UTC, rootCurse commented on homework1/quickSort.ts
> +    }
Переписать для выбора pivot центральным

2024-10-18 07:13 UTC, rootCurse commented on homework1/binarySearch.ts
> +function binarySearch(arr: Array<number>, x: number) {
Рекурсивно с формулой (left + right) /2

2024-10-24 16:10 UTC, theCrystalKitty commented on homework1/insertionSort.ts
> +//Difficulty: O(n log(n))
Исправлено

2024-10-24 16:10 UTC, theCrystalKitty commented on homework1/binarySearch.ts
> +function binarySearch(arr: Array<number>, x: number) {
Переписано

2024-10-24 16:12 UTC, theCrystalKitty commented on homework1/quickSort.ts
> +    }
Pivot нельзя делать центральным, иначе сортировка не будет работать. pivot может быть первым элементом, последним или средним среди всех значений в массиве. У меня вариант с выбором pivot последнего элемента

2024-10-25 05:35 UTC, merged